# Uncomment the next line to define a global platform for your project
platform :ios, '11.3'
source 'https://github.com/CocoaPods/Specs.git'

target 'ConwayNetWork' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # source 'https://github.com/CocoaPods/Specs.git'

  pod 'Starscream', '~> 3.0.2'

  # Pods for ConwayNetWork

  target 'ConwayNetWorkTests' do
    inherit! :search_paths
    # Pods for testing
    # pod 'Starscream', '~> 3.0.2'
  end

end
